### ISSUE TITLE
Проблема с TTS 

### ISSUE THREAD

**Issue by Kanorto** [Priler/jarvis#10]
При запуске Main.py выдают ошибку. Я не нашел, как установить эту библиотеку. Гайд для виндовс не работает, так как нету файла TEST_CUDA
Using cache found in C:\Users\Лев/.cache\torch\hub\snakers4_silero-models_master
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    import tts
  File "C:\Users\Лев\Desktop\JARVIS\tts.py", line 14, in <module>
    model, _ = torch.hub.load(repo_or_dir='snakers4/silero-models',
  File "C:\Program Files\Python38\lib\site-packages\torch\hub.py", line 399, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\torch\hub.py", line 428, in _load_local
    model = entry(*args, **kwargs)
  File "C:\Users\Лев/.cache\torch\hub\snakers4_silero-models_master\src\silero\silero.py", line 87, in silero_tts
    imp = package.PackageImporter(model_path)
  File "C:\Program Files\Python38\lib\site-packages\torch\package\package_importer.py", line 75, in __init__
    self.zip_reader = torch._C.PyTorchFileReader(self.filename)
RuntimeError: open file failed because of errno 2 on fopen: No such file or directory, file path: C:\Users\Лев/.cache\torch\hub\snakers4_silero-models_master\src\silero\model\ru_v3.pt

**Comment by Kanorto** [comment]
при попытке установке TTS Ошибка


 D:\temp\pro\VC\Tools\MSVC\14.35.32215\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Лев\AppData\Local\Temp\pip-build-env-mw4mty2p\overlay\Lib\site-packages\numpy\core\include "-IC:\Program Files\Python38\include" "-IC:\Program Files\Python38\Include" -ID:\temp\pro\VC\Tools\MSVC\14.35.32215\include -ID:\temp\pro\VC\Tools\MSVC\14.35.32215\ATLMFC\include -ID:\temp\pro\VC\Auxiliary\VS\include "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /TcTTS/tts/utils/monotonic_align/core.c /Fobuild\temp.win-amd64-cpython-38\Release\TTS/tts/utils/monotonic_align/core.obj
      core.c
      C:\Program Files\Python38\include\pyconfig.h(206): fatal error C1083: ЌҐ г¤ Ґвбп ®вЄалвм д ©« ўЄ«озҐ­ЁҐ: basetsd.h: No such file or directory,
      C:\Users\Лев\AppData\Local\Temp\pip-build-env-mw4mty2p\overlay\Lib\site-packages\setuptools\command\build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'TTS.vocoder.configs' as data is deprecated, please list it in `packages`.
          !!


          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'TTS.vocoder.configs' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.

          'TTS.vocoder.configs' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).

          Please make sure that 'TTS.vocoder.configs' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" and "data files" on setuptools
          documentation page.


      !!

        check.warn(importable)
      C:\Users\Лев\AppData\Local\Temp\pip-build-env-mw4mty2p\overlay\Lib\site-packages\setuptools\command\build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'TTS.vocoder.datasets' as data is deprecated, please list it in `packages`.
          !!


          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'TTS.vocoder.datasets' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.

          'TTS.vocoder.datasets' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).

          Please make sure that 'TTS.vocoder.datasets' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" and "data files" on setuptools
          documentation page.


      !!

        check.warn(importable)
      C:\Users\Лев\AppData\Local\Temp\pip-build-env-mw4mty2p\overlay\Lib\site-packages\setuptools\command\build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'TTS.vocoder.layers' as data is deprecated, please list it in `packages`.
          !!


          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'TTS.vocoder.layers' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.

          'TTS.vocoder.layers' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).

          Please make sure that 'TTS.vocoder.layers' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" and "data files" on setuptools
          documentation page.


      !!

        check.warn(importable)
      C:\Users\Лев\AppData\Local\Temp\pip-build-env-mw4mty2p\overlay\Lib\site-packages\setuptools\command\build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'TTS.vocoder.models' as data is deprecated, please list it in `packages`.
          !!


          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'TTS.vocoder.models' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.

          'TTS.vocoder.models' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).

          Please make sure that 'TTS.vocoder.models' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" and "data files" on setuptools
          documentation page.


      !!

        check.warn(importable)
      C:\Users\Лев\AppData\Local\Temp\pip-build-env-mw4mty2p\overlay\Lib\site-packages\setuptools\command\build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'TTS.vocoder.utils' as data is deprecated, please list it in `packages`.
          !!


          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'TTS.vocoder.utils' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.

          'TTS.vocoder.utils' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).

          Please make sure that 'TTS.vocoder.utils' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" and "data files" on setuptools
          documentation page.


      !!

        check.warn(importable)
      error: command 'D:\\temp\\pro\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for TTS
Failed to build TTS
ERROR: Could not build wheels for TTS, which is required to install pyproject.toml-based projects
