### ISSUE TITLE
Помогите с билдом

### ISSUE THREAD

**Issue by Dymkar** [Priler/jarvis#100]
Я попытался сбилдить джарвиса, установив нужные модули но появилось это:

```
▲ [WARNING] Cannot find base config file "@tsconfig/svelte/tsconfig.json" [tsconfig.json]

    tsconfig.json:2:13:
      2 │   "extends": "@tsconfig/svelte/tsconfig.json",
        ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[tsconfig-paths] An error occurred while parsing "F:\jarvis-master\gui\tsconfig.json". See below for details. To disable this message, set the `ignoreConfigErrors` option to true.
TSConfckParseError: failed to resolve "extends":"@tsconfig/svelte/tsconfig.json" in F:\jarvis-master\gui\tsconfig.json
    at resolveExtends (file:///F:/jarvis-master/node_modules/tsconfck/dist/index.js:496:9)
    at parseExtends (file:///F:/jarvis-master/node_modules/tsconfck/dist/index.js:450:28)
    ... 5 lines matching cause stack trace ...
    at async _createServer (file:///F:/jarvis-master/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:63274:20)
    at async CAC.<anonymous> (file:///F:/jarvis-master/node_modules/vite/dist/node/cli.js:733:24) {
  code: 'EXTENDS_RESOLVE',
  cause: Error: Cannot find module '@tsconfig\svelte\tsconfig.json\tsconfig.json'
  Require stack:
  - F:\jarvis-master\gui\tsconfig.json
      at Module._resolveFilename (node:internal/modules/cjs/loader:1070:15)
      at Function.resolve (node:internal/modules/helpers:127:19)
      at resolveExtends (file:///F:/jarvis-master/node_modules/tsconfck/dist/index.js:491:34)
      at parseExtends (file:///F:/jarvis-master/node_modules/tsconfck/dist/index.js:450:28)
      at Module.parse (file:///F:/jarvis-master/node_modules/tsconfck/dist/index.js:388:24)
      at async Promise.all (index 0)
      at async configResolved (file:///F:/jarvis-master/node_modules/vite-tsconfig-paths/dist/index.mjs:98:10)
      at async Promise.all (index 2)
      at async resolveConfig (file:///F:/jarvis-master/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:64253:5)
      at async _createServer (file:///F:/jarvis-master/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:63274:20) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [ 'F:\\jarvis-master\\gui\\tsconfig.json' ]
  },
  tsconfigFile: 'F:\\jarvis-master\\gui\\tsconfig.json'
}
Forced re-optimization of dependencies

  VITE v4.3.9  ready in 462 ms

  ➜  Local:   http://localhost:1420/
  ➜  Network: use --host to expose
Error: The following dependencies are imported but could not be resolved:

  @svelteuidev/core (imported by F:/jarvis-master/gui/src/pages/settings.svelte?id=0)
  @tauri-apps/api/tauri (imported by F:/jarvis-master/gui/src/Events.svelte?id=0)
  @/components/Header.svelte (imported by F:/jarvis-master/gui/src/pages/_layout.svelte?id=0)
  @/components/elements/HDivider.svelte (imported by F:/jarvis-master/gui/src/pages/settings.svelte?id=0)
  @/components/Footer.svelte (imported by F:/jarvis-master/gui/src/pages/settings.svelte?id=0)
  @/stores (imported by F:/jarvis-master/gui/src/Events.svelte?id=0)
  @tauri-apps/api/event (imported by F:/jarvis-master/gui/src/Events.svelte?id=0)
  @tauri-apps/api/path (imported by F:/jarvis-master/gui/src/Events.svelte?id=0)
  @/components/elements/SearchBar.svelte (imported by F:/jarvis-master/gui/src/pages/index.svelte?id=0)
  @/functions (imported by F:/jarvis-master/gui/src/pages/settings.svelte?id=0)
  @/components/elements/ArcReactor.svelte (imported by F:/jarvis-master/gui/src/pages/index.svelte?id=0)
  worker-timers (imported by F:/jarvis-master/gui/src/pages/settings.svelte?id=0)
  radix-icons-svelte (imported by F:/jarvis-master/gui/src/pages/settings.svelte?id=0)
  @/components/elements/Stats.svelte (imported by F:/jarvis-master/gui/src/pages/index.svelte?id=0)
  howler (imported by F:/jarvis-master/gui/src/Events.svelte?id=0)

Are they installed?
    at file:///F:/jarvis-master/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:44188:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///F:/jarvis-master/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:43597:38
        Info Watching F:\jarvis-master\gui\src-tauri for changes...
    Updating crates.io index
  Downloaded ordered-float v1.1.1
  Downloaded num v0.1.42
  Downloaded log-mdc v0.1.0
  Downloaded ogg v0.8.0
  Downloaded linked-hash-map v0.5.6
  Downloaded arc-swap v0.4.8
  Downloaded platform-dirs v0.3.0
  Downloaded primal-check v0.3.3
  Downloaded bitflags v0.7.0
  Downloaded realfft v3.3.0
  Downloaded ciborium-io v0.2.1
  Downloaded arc-swap v1.6.0
  Downloaded arrayvec v0.7.2
  Downloaded atomic_enum v0.2.0
  Downloaded vosk-sys v0.1.1
  Downloaded thread-id v3.3.0
  Downloaded simple-log v1.6.0
  Downloaded tauri-build v1.3.0
  Downloaded serde-value v0.6.0
  Downloaded symphonia v0.5.3
  Downloaded is_debug v1.0.1
  Downloaded dasp_sample v0.11.0
  Downloaded quick-error v1.2.3
  Downloaded convert_case v0.5.0
  Downloaded ciborium-ll v0.2.1
  Downloaded seqdiff v0.3.0
  Downloaded dirs-next v1.0.2
  Downloaded vosk v0.2.0
  Downloaded humantime v1.3.0
  Downloaded symphonia-metadata v0.5.3
  Downloaded strength_reduce v0.2.4
  Downloaded serde_with_macros v2.3.3
  Downloaded transpose v0.2.2
  Downloaded portaudio v0.7.0
  Downloaded parking_lot_core v0.8.6
  Downloaded parking_lot v0.11.2
  Downloaded hound v3.5.0
  Downloaded half v1.8.2
  Downloaded time v0.1.45
  Downloaded libloading v0.7.4
  Downloaded serde_yaml v0.8.26
  Downloaded toml v0.7.3
  Downloaded rodio v0.17.1
  Downloaded yaml-rust v0.4.5
  Downloaded ciborium v0.2.1
  Downloaded log v0.4.18
  Downloaded tauri-utils v1.3.0
  Downloaded uuid v1.3.3
  Downloaded symphonia-bundle-mp3 v0.5.3
  Downloaded rubato v0.12.0
  Downloaded log4rs v0.13.0
  Downloaded claxon v0.4.3
  Downloaded lewton v0.10.2
  Downloaded symphonia-core v0.5.3
  Downloaded toml_edit v0.19.8
  Downloaded winnow v0.4.1
  Downloaded cpal v0.15.2
  Downloaded serde_with v2.3.3
  Downloaded serde_json v1.0.96
  Downloaded rustpotter v2.0.0
  Downloaded rustfft v6.1.0
  Downloaded pv_porcupine v2.2.1
  Downloaded pv_recorder v1.1.2
  Downloaded windows v0.46.0
  Downloaded 64 crates (20.6 MB) in 41.20s (largest was `windows` at 11.7 MB)
   Compiling proc-macro2 v1.0.60
   Compiling quote v1.0.28
   Compiling unicode-ident v1.0.9
   Compiling cfg-if v1.0.0
   Compiling autocfg v1.1.0
   Compiling serde v1.0.164
   Compiling ppv-lite86 v0.2.17
   Compiling syn v1.0.109
   Compiling siphasher v0.3.10
   Compiling getrandom v0.1.16
   Compiling smallvec v1.10.0
   Compiling libc v0.2.146
   Compiling phf_shared v0.8.0
   Compiling getrandom v0.2.10
   Compiling windows_x86_64_msvc v0.48.0
   Compiling winapi v0.3.9
   Compiling rand_core v0.6.4
   Compiling scopeguard v1.1.0
   Compiling proc-macro-hack v0.5.20+deprecated
   Compiling phf_shared v0.10.0
   Compiling num-traits v0.2.15
   Compiling lock_api v0.4.10
   Compiling rand_chacha v0.3.1
   Compiling rand v0.8.5
   Compiling indexmap v1.9.3
   Compiling parking_lot_core v0.9.8
   Compiling fnv v1.0.7
   Compiling windows-targets v0.48.0
   Compiling hashbrown v0.12.3
   Compiling rand_core v0.5.1
   Compiling syn v2.0.18
   Compiling rand_chacha v0.2.2
   Compiling rand_pcg v0.2.1
   Compiling phf_generator v0.10.0
   Compiling byteorder v1.4.3
   Compiling rand v0.7.3
   Compiling num-integer v0.1.45
   Compiling once_cell v1.18.0
   Compiling bitflags v1.3.2
   Compiling serde_json v1.0.96
   Compiling ryu v1.0.13
   Compiling itoa v1.0.6
   Compiling tinyvec_macros v0.1.1
   Compiling log v0.4.18
   Compiling new_debug_unreachable v1.0.4
   Compiling tinyvec v1.6.0
   Compiling string_cache_codegen v0.5.2
   Compiling mac v0.1.1
   Compiling ident_case v1.0.1
   Compiling parking_lot v0.12.1
   Compiling phf_generator v0.8.0
   Compiling strsim v0.10.0
   Compiling phf_codegen v0.8.0
   Compiling cc v1.0.79
   Compiling semver v1.0.17
   Compiling precomputed-hash v0.1.1
   Compiling markup5ever v0.10.1
   Compiling futf v0.1.5
   Compiling utf-8 v0.7.6
   Compiling winnow v0.4.1
   Compiling dtoa v1.0.6
   Compiling dtoa-short v0.3.4
   Compiling tendril v0.4.3
   Compiling selectors v0.22.0
   Compiling matches v0.1.10
   Compiling itoa v0.4.8
   Compiling convert_case v0.4.0
   Compiling stable_deref_trait v1.2.0
   Compiling nodrop v0.1.14
   Compiling windows_x86_64_msvc v0.39.0
   Compiling thiserror v1.0.40
   Compiling servo_arc v0.1.1
   Compiling unicode-normalization v0.1.22
   Compiling fxhash v0.2.1
   Compiling unicode-bidi v0.3.13
   Compiling thin-slice v0.1.1
   Compiling version_check v0.9.4
   Compiling windows_x86_64_msvc v0.42.2
   Compiling windows-tokens v0.39.0
   Compiling uuid v1.3.3
   Compiling vswhom-sys v0.1.2
   Compiling memchr v2.5.0
   Compiling percent-encoding v2.3.0
   Compiling rustfft v6.1.0
   Compiling cfb v0.7.3
   Compiling form_urlencoded v1.2.0
   Compiling idna v0.4.0
   Compiling darling_core v0.20.1
   Compiling rustc_version v0.4.0
   Compiling lazy_static v1.4.0
   Compiling parking_lot_core v0.8.6
   Compiling winapi-util v0.1.5
   Compiling same-file v1.0.6
   Compiling winreg v0.11.0
   Compiling strength_reduce v0.2.4
   Compiling bytemuck v1.13.1
   Compiling anyhow v1.0.71
   Compiling arrayvec v0.7.2
   Compiling crc32fast v1.3.2
   Compiling infer v0.12.0
   Compiling transpose v0.2.2
   Compiling walkdir v2.3.3
   Compiling primal-check v0.3.3
   Compiling num-complex v0.4.3
   Compiling num-iter v0.1.43
   Compiling vswhom v0.1.0
   Compiling encoding_rs v0.8.32
   Compiling instant v0.1.12
   Compiling glob v0.3.1
   Compiling linked-hash-map v0.5.6
   Compiling pkg-config v0.3.27
   Compiling adler v1.0.2
   Compiling miniz_oxide v0.7.1
   Compiling yaml-rust v0.4.5
   Compiling windows-targets v0.42.2
   Compiling time v0.1.45
   Compiling ordered-float v1.1.1
   Compiling quick-error v1.2.3
   Compiling portaudio v0.7.0
   Compiling heck v0.4.1
   Compiling half v1.8.2
   Compiling ciborium-io v0.2.1
   Compiling cpal v0.15.2
   Compiling chrono v0.4.26
   Compiling ciborium-ll v0.2.1
   Compiling humantime v1.3.0
   Compiling flate2 v1.0.26
   Compiling windows v0.46.0
   Compiling parking_lot v0.11.2
   Compiling thread-id v3.3.0
   Compiling dirs-sys-next v0.1.2
   Compiling serde_derive v1.0.164
   Compiling cssparser-macros v0.6.1
   Compiling thiserror-impl v1.0.40
   Compiling libloading v0.7.4
   Compiling darling_macro v0.20.1
   Compiling ogg v0.8.0
   Compiling dasp_sample v0.11.0
   Compiling pv_recorder v1.1.2
   Compiling darling v0.20.1
   Compiling serde_with_macros v2.3.3
   Compiling log-mdc v0.1.0
   Compiling hound v3.5.0
   Compiling phf_macros v0.8.0
   Compiling cssparser v0.27.2
   Compiling html5ever v0.25.2
   Compiling derive_more v0.99.17
   Compiling windows-implement v0.39.0
   Compiling phf_macros v0.10.0
   Compiling ctor v0.1.26
   Compiling pv_porcupine v2.2.1
   Compiling phf v0.8.0
   Compiling arc-swap v0.4.8
   Compiling windows v0.39.0
   Compiling phf v0.10.1
   Compiling lewton v0.10.2
   Compiling dirs-next v1.0.2
   Compiling num v0.1.42
   Compiling convert_case v0.5.0
   Compiling claxon v0.4.3
   Compiling vosk-sys v0.1.1
   Compiling is_debug v1.0.1
   Compiling bitflags v0.7.0
   Compiling platform-dirs v0.3.0
   Compiling atomic_enum v0.2.0
   Compiling realfft v3.3.0
   Compiling rubato v0.12.0
   Compiling arc-swap v1.6.0
   Compiling seqdiff v0.3.0
   Compiling toml_datetime v0.6.2
   Compiling serde_spanned v0.6.2
   Compiling string_cache v0.8.7
   Compiling url v2.4.0
   Compiling serde_with v2.3.3
   Compiling serde_yaml v0.8.26
   Compiling serde-value v0.6.0
   Compiling ciborium v0.2.1
   Compiling toml_edit v0.19.8
   Compiling symphonia-core v0.5.3
   Compiling rustpotter v2.0.0
   Compiling symphonia-metadata v0.5.3
   Compiling symphonia-bundle-mp3 v0.5.3
   Compiling toml v0.7.3
   Compiling simple-log v1.6.0
   Compiling kuchiki v0.8.1
   Compiling embed-resource v2.1.1
   Compiling cargo_toml v0.15.3
   Compiling symphonia v0.5.3
   Compiling tauri-utils v1.3.0
   Compiling tauri-winres v0.1.1
   Compiling tauri-build v1.3.0
   Compiling jarvis-app v0.0.3 (F:\jarvis-master\gui\src-tauri)
error: failed to run custom build command for `jarvis-app v0.0.3 (F:\jarvis-master\gui\src-tauri)`

Caused by:
  process didn't exit successfully: `F:\jarvis-master\gui\src-tauri\target\debug\build\jarvis-app-ce471d42f62dca44\build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rerun-if-changed=tauri.conf.json
  cargo:rustc-cfg=desktop
  cargo:rustc-cfg=dev
  path matching commands not found.
warning: build failed, waiting for other jobs to finish...
```
Помогите пожалуйста

**Comment by loop-lab** [comment]
Удалось сбилдить?

**Comment by GoodAlien** [comment]
Проблема актуальна!
Кто разбирается помогите решить.
