### ISSUE TITLE
При запуске выдаёт ошибку

### ISSUE THREAD

**Issue by harchock** [Priler/jarvis#14]
`C:\Users\Михаил\Desktop\jarvis-master>python main.py
Using cache found in C:\Users\Михаил/.cache\torch\hub\snakers4_silero-models_master
Traceback (most recent call last):
  File "main.py", line 27, in <module>
    import tts
  File "C:\Users\Михаил\Desktop\jarvis-master\tts.py", line 15, in <module>
    model, _ = torch.hub.load(repo_or_dir='snakers4/silero-models',
  File "C:\Users\Михаил\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\hub.py", line 558, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "C:\Users\Михаил\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\hub.py", line 587, in _load_local
    model = entry(*args, **kwargs)
  File "C:\Users\Михаил/.cache\torch\hub\snakers4_silero-models_master\src\silero\silero.py", line 87, in silero_tts
    imp = package.PackageImporter(model_path)
  File "C:\Users\Михаил\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\package\package_importer.py", line 95, in __init__
    self.zip_reader = torch._C.PyTorchFileReader(self.filename)
RuntimeError: open file failed because of errno 2 on fopen: No such file or directory, file path: C:\Users\Михаил/.cache\torch\hub\snakers4_silero-models_master\src\silero\model\ru_v3.pt`

**Comment by harchock** [comment]
Я сделал всё по инструкции, и выдаёт эту ошибку

**Comment by dimitrieidifesk** [comment]
Латиница в пути к файлу. Скопируй в snakers4_silero-models_master папку src и файл hubconf.py в корневую папку Джарвиса. В файле tts.py на 15 строчке измени значение параметра repo_or_dir на '.'

**Comment by dimitrieidifesk** [comment]
Возможно придется добавить параметр source="Local"
В общем случае должно получится так
model, _ = torch.hub.load(repo_or_dir='.',
                          model='silero_tts',
                          source="Local",
                          language=language,
                          speaker=model_id)

**Comment by harchock** [comment]
`C:\Users\Михаил\Desktop\jarvis-master>python main.py
Traceback (most recent call last):
  File "main.py", line 46, in <module>
    porcupine = pvporcupine.create(
  File "C:\Users\Михаил\AppData\Local\Programs\Python\Python38\lib\site-packages\pvporcupine\_factory.py", line 69, in create
    return Porcupine(
  File "C:\Users\Михаил\AppData\Local\Programs\Python\Python38\lib\site-packages\pvporcupine\_porcupine.py", line 123, in __init__
    raise ValueError("access_key should be a non-empty string.")
ValueError: access_key should be a non-empty string.`
Теперь выдало эту ошибку
сделал всё как ты сказал

**Comment by xlebushek-bit** [comment]
Как решили эту проблему?
