### ISSUE TITLE
Помогите с ошибкой

### ISSUE THREAD

**Issue by harchock** [Priler/jarvis#17]
`C:\Users\Михаил\Desktop\jarvis-master>python main.py
Traceback (most recent call last):
  File "main.py", line 46, in <module>
    porcupine = pvporcupine.create(
  File "C:\Users\Михаил\AppData\Local\Programs\Python\Python38\lib\site-packages\pvporcupine\_factory.py", line 69, in create
    return Porcupine(
  File "C:\Users\Михаил\AppData\Local\Programs\Python\Python38\lib\site-packages\pvporcupine\_porcupine.py", line 123, in __init__
    raise ValueError("access_key should be a non-empty string.")
ValueError: access_key should be a non-empty string.`

сама ошибка
я делал всё по инструкции

**Comment by dimitrieidifesk** [comment]
Приватный ключ в переменной окружения укажи. В файле config.env

**Comment by harchock** [comment]
> 

Я указал приватный ключ
я делал всё по инструкции.
но оно выдаёт ошибку именно из за этого ключа.
Я пробовал немного переделать код получалась другая ошибка
`C:\Users\Михаил\Desktop\jarvis-master>python main.py
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    config.environ.get('PICOVOICE_TOKEN'),
AttributeError: module 'config' has no attribute 'environ'`

**Comment by Kanorto** [comment]
Получилось решить?
