### ISSUE TITLE
ValueError: access_key should be a non-empty string.

### ISSUE THREAD

**Issue by aiivy782** [Priler/jarvis#28]
```
Using cache found in C:\Users\user/.cache\torch\hub\snakers4_silero-models_master
Traceback (most recent call last):
  File "F:\Repositories\jarvis\main.py", line 44, in <module>
    porcupine = pvporcupine.create(
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pvporcupine\_factory.py", line 69, in create
    return Porcupine(
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pvporcupine\_porcupine.py", line 123, in __init__
    raise ValueError("access_key should be a non-empty string.")
ValueError: access_key should be a non-empty string.
```
Windows 11 x64, Python 3.10.11

**Comment by WindEger** [comment]
Нашел решение этой проблемы. В config.py должно быть:
PICOVOICE_TOKEN = 'Сюда ключ picovoice'
нужно стереть скобки и os.getenv

**Comment by aiivy782** [comment]
Да, если убрать os.getenv функцию, то всё работает прекрасно, спасибо)

**Comment by RoldexX** [comment]
Соре, я действительно ввёл вас в заблуждение, верните файл config.py в исходное состояние и перенесите токены в файл dev.env (сразу после равно без скобочек <>)
