### ISSUE TITLE
python version 3.10.11 ValueError in pvrecorder

### ISSUE THREAD

**Issue by MuhammadKasimov** [Priler/jarvis#35]
```Traceback (most recent call last):
  File "C:\Users\muham\jarvis\main.py", line 20, in <module>
    from pvrecorder import PvRecorder
  File "C:\Users\muham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pvrecorder\__init__.py", line 12, in <module>     
    from .pvrecorder import PvRecorder
  File "C:\Users\muham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pvrecorder\pvrecorder.py", line 20, in <module>   
    class PvRecorder(object):
  File "C:\Users\muham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pvrecorder\pvrecorder.py", line 203, in PvRecorder
    _LIBRARY = cdll.LoadLibrary(_lib_path.__func__())
  File "C:\Users\muham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pvrecorder\pvrecorder.py", line 192, in _lib_path 
    os_name, cpu = str(command.stdout.decode("utf-8")).split(" ")
ValueError: too many values to unpack (expected 2)```

**Comment by xtrysa** [comment]
pip install pvrecorder, напиши вставь это  в консоль

**Comment by MuhammadKasimov** [comment]
> pip install pvrecorder, напиши вставь это в консоль

pvrecorder установлен ошибка в том что с метода decode возвращается более двух аргументов

**Comment by MuhammadKasimov** [comment]
кроме того проблема оказалась в консоли
ошибка исправлена
