### ISSUE TITLE
Ошибка 

### ISSUE THREAD

**Issue by Klsvvv2** [Priler/jarvis#79]
При любой команде вылазит эта ошибка
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "Не удается найти указанный файл." }', src\tauri_commands\voice.rs:14:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by Priler** [comment]
Ошибка известна.
Исправим в ближайшем обновлении.

**Comment by el1sha-git** [comment]
в общем получилось собрать на linux :) и запустить, на команду jarvis отвечает, когда подключается vosk вылазит эта ошибка

thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("key must be a string", line: 3, column: 26)', /home/nobody/.cargo/registry/src/github.com-1ecc6299db9ec823/vosk-0.2.0/src/recognition/mod.rs:258:10
